apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-convert
  labels:
    app: convert
spec:
  replicas: 1
  selector:
    matchLabels:
      app: convert
  template:
    metadata:
      labels:
        app: convert
    spec:
      containers:
        - name: convert
          imagePullPolicy: Always
          image: 192.168.48.138:6000/convert:latest
          ports:
            - containerPort: 5000
        
---
apiVersion: v1
kind: Service
metadata:
  name: svc-convert
spec:
  type: NodePort
  selector:
    app: convert
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30003
